```{r}
library("tidyverse")
library("broom")
library("ggplot2")
```

```{r}
#
cancer_data <- read_csv("../data/03_expression_tidy.csv")
cancer_data_scaled <- read_csv("../data/03_expression_scaled.csv")
```

```{r}
# Perform PCA
pca_fit <- cancer_data_scaled |>
  select(!c(1:3)) |>  # Retain only numeric columns
  prcomp(scale = FALSE)  # Perform PCA on scaled data
```

```{r}
pca_fit |> 
  tidy(matrix = "eigenvalues")
```

```{r}
variance_95 <- pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  arrange() |> 
  filter(cumulative < 0.95)
```

```{r}
# Bar plot for 95% PCs
variance_95 |> 
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous() +
  scale_y_continuous(
    labels = scales::percent_format()) +
  labs(title = "95% of Variance Percentage", 
       x = "PCs",
       y = "Percentage of Variance") +
  theme_minimal_hgrid(15)
```

```{r}
# Bar plot for first two PCs
first_two_pc <- variance_95 |> 
  filter(PC<3) 
first_two_pc |> 
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_discrete(limits = c("1", "2")) + 
  scale_y_continuous() +
  labs(title = "Variance Percentage for first two PCs", 
       x = "PCs",
       y = "Percentage of Variance") +
  theme_minimal_hgrid(15)
```

